### ISSUE TITLE
drone 安装

### ISSUE THREAD

**Issue by iliuyt** [iliuyt/blog#71]
## 简介

Drone是一个方便快捷的持续集成软件，可以通过docker进行安装部署到不同的平台上，通过pipeline定制流程，可读性非常好。支持github、gitlab、gogs、gitea平台。启动快，占用资源少，还有大量插件可以使用。

## 官网

https://docs.drone.io/

## 使用场景

drone 适用于创业团队、兼职团队、个人开发者，特性为快速搭建，使用方便，对机器的要求也很低，非常适合个人开发者。

## 准备

* 获取gitea clientID和密钥
* 进入gitea,点击 个人信息头像->设置->应用->管理 OAuth2 应用程序->创建应用
* 输入应用名称和地址,地址为drone服务器地址，注意要/login结尾，举例 http://drone.iliuyt.comlogin

### docker-compose 脚本

```
version: "3"

services:
  drone-server:
    container_name: drone-server
    image: drone/drone:latest
    ports:
      - 1443:443
      - 8888:80
    volumes:
      - ./data:/data:rw
    restart: always
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=drone.shushidata.com
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=Uu123456
      - DRONE_USER_CREATE=username:root,admin:true
      - DRONE_GITEA_SERVER=http://git.shushidata.com
      - DRONE_GITEA_CLIENT_ID=a18217a6-a24c-4f99-8b5d-7829e5f01b3c
      - DRONE_GITEA_CLIENT_SECRET=Ey6TWlhhmsQu7zITfa12Lj8FyhsTNqMoyT8yL0Fw47o=
```

### 启动docker

```
docker-compose up -d
```

### 注意

* 如果不设置DRONE_USER_CREATE会导致无法构建，DRONE_USER_CREATE需要设置Gitea的用户为管理员

### 官方文档

https://docs.drone.io/runner/exec/installation/linux/

### 安装

Download for amd64 architectures:

```
$ curl -L https://github.com/drone-runners/drone-runner-exec/releases/latest/download/drone_runner_exec_linux_amd64.tar.gz | tar zx
$ sudo install -t /usr/local/bin drone-runner-exec
```

### 配置

配置文档：https://docs.drone.io/runner/exec/configuration/reference/

```
echo >/var/log/drone-runner-exec/drone.log
vim /etc/drone-runner-exec/config

# 配置内容
DRONE_RPC_PROTO=http
DRONE_RPC_HOST=drone.shushidata.com
DRONE_RPC_SECRET=Uu123456
DRONE_LOG_FILE=/data/log/drone/drone.log
```

### 服务安装与启动

```
$ drone-runner-exec service install
$ drone-runner-exec service start
```

### 服务启动验证

```
$ cat /var/log/drone-runner-exec/log.txt

INFO[0000] starting the server
INFO[0000] successfully pinged the remote server
```
